{{- if and .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
{{- if .Valuesrbac.serviceAccount }}
  name: {{ .Valuesrbac.serviceAccount }}
{{- else }}
  name: {{ template "logrotate.name" . }}
{{- end }}
{{- end }}
